### ISSUE TITLE
Refactor REDCap hook deployment to allow single feature to deploy multiple hooks with different hook functions

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_deployment#10]
Refactor REDCap hook deployment to allow single feature to deploy multiple hooks with different hook functions. The current design requires deployment script to be associated with a single hook function. This makes the deployment of feature that needs to use different hook types needless confusing and complex.  

For example, a data entry hook that adds an action tag would benefit from another hook that added the help text for the new action tag in the online form builder. Yet these two hooks should use different hook functions. 

I propose a new design wherein the deploy/hooks folder has sub-folders that name features. Each features _must_ have an deploy.sh file. That deploy.sh must know which hook type to use for each component of the hook. It must place hooks in the correct sub-folder in the hook library.

**Comment by marlycormar** [comment]
This feature is ready to be tested. The commits have been deployed to the *feature* branch `refactor_hooks_deployment`.

**Comment by pbchase** [comment]
This was merged on 7/20/2017 in commit fcbe3c5.
