### ISSUE TITLE
Phase out support for redcap hooks

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_deployment#31]
REDCap external modules have vastly simplified the packaging, distribution, deployment, and configuration of REDCap hooks. As such there is little value for direct support of hooks and hook frameworks. I propose that we completely remove hook support from these tools after all of the hooks referenced here are replaced with modules. 

This would entail removal of every hook deployment script, the hook framework deployment script, hook.py, package::deploy_hook*, utility_redcap::set_hook*, every reference to those hook methods in the fabric code, every reference to hooks in the config files, and every reference to hooks in the documentation.

**Comment by pbchase** [comment]
@marlycormar, @tbembersimeao, what do you think?  Should we go this far?

**Comment by tbembersimeao** [comment]
@pbchase I don't see any reason to keep giving support to hooks. As you said, external modules is the way to go and made the former approach deprecated.

**Comment by pbchase** [comment]
All support for hook packaging, deployment and activation has been removed as of release 2.0.0
