### ISSUE TITLE
orca_search module dies during upgrades

### ISSUE THREAD

**Issue by pbchase** [ctsit/redcap_deployment#64]
The orca_search module, https://github.com/dr01d3r/redcap-em-orca-search, dies during upgrades that are managed by redcap_deployment. The error is that orca_search can't write to `/var/www.backup/redcap-20190718T2033/modules/orca_search_v2.0.0/templates_c/4ad6cd8f7cfdbb05b6b8f75fc41bbd19f5d1745c_0.file.orca_search.tpl.php` When redcap_deployment does an upgrade it changes the perms of `templates_c` to group:read while changing the ownership to `deploy` instead of `www-data`. At the same time `4ad6cd8f7cfdbb05b6b8f75fc41bbd19f5d1745c_0.file.orca_search.tpl.php` is set to read-only for `www-data`. 

To fix this issue, redcap_deployment needs to be more subtle WRT to the ownership and perms for this module in much the same way as it handles the redcap temp folder. Consider changes near this line: https://github.com/ctsit/redcap_deployment/blob/602cb1d26efd8a22c0ae0c841d11e3f5ddcf813f/utility_redcap.py#L61 or this line: https://github.com/ctsit/redcap_deployment/blob/602cb1d26efd8a22c0ae0c841d11e3f5ddcf813f/utility_redcap.py#L83

**Comment by pbchase** [comment]
@dr01d3r, we ran into a problem with Orca Search last night during a REDCap upgrade. I'm 100% sure it was our deployment tool that caused the problem, but could you take a look at my description of the issue above? I want to be sure I understand what orca_search needs. 

FYI, I was able to fix the problem with a few file permission changes, so I think I understand what's going on, but I'd appreciate your input.

**Comment by dr01d3r** [comment]
@pbchase, `templates_c` is a cache folder used by the Smarty templating package.  The module configures this when the plugin page loads.

https://github.com/dr01d3r/redcap-em-orca-search/blob/b7c275ec1f1da240369aa944653a302c0bc032ac/OrcaSearch.php#L53

This folder can be deleted at any time, and the next time a request is made to render the plugin page, those files will be recreated, if necessary.

I would suggest you delete or omit `templates_c` from your migration, and let the module recreate it, the next time it loads.  As long as it inherits the normally required permissions of the `modules` folder, it should be fine.

This will hold true for other modules that use Smarty, or write to their local directory structure.  I know of at least 1 other module that uses Smarty, and they use the same folder name, but per my link above, it is up to us what we call it.  You may have to handle this on a case-by-case basis.

**Comment by pbchase** [comment]
@dr01d3r, thanks for the feedback. We'll try to implement this the way you suggest to allow the modules to write to their own directories.

**Comment by pbchase** [comment]
Addressed by PR #71
