### ISSUE TITLE
Forbidden page text change for Resources folders causes tests to fail for REDCap 11+

### ISSUE THREAD

**Issue by ChemiKyle** [ctsit/redcap_deployment#74]
I'm not sure of the actual version change, but the text for 403 errors changed causing failures for our tests in 5/6 tests that check on access `Resources` and its subdirectories.

```
rg -t py "localpath = \"Resources.*" -B2 | grep def
tests/test.py-    def testResourceFolder(self):
tests/test.py-    def testCssFolder(self):
tests/test.py-    def testJsFolder(self):
tests/test.py-    def testImagesFolder(self):
tests/test.py-    def testMiscFolder(self):
tests/test.py-    def testSqlFolder(self):
```

https://github.com/ctsit/redcap_deployment/blob/602cb1d26efd8a22c0ae0c841d11e3f5ddcf813f/tests/test.py#L31-L38

Can be replaced with:

```py
        self.rc_forbidden = '''<!DOCTYPE HTML>
<html>
<head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this page.</p></body>
</html>
'''
```

Perhaps the version should be pinpointed and `self.rc_forbidden` should be intelligently defined, or we can just check for the text "403 forbidden".

---

`testMiscFolder` doesn't actually fail, but it doesn't expect `rc_forbidden`

**Comment by pbchase** [comment]
This was fixed in commit cc3fab3
